steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    'dummy',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-registry/dummy',
    '-f',
    'dummy/Dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-registry/dummy'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
