name: DVC Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.dvc"
      - ".dvc/**"

jobs:
  run-data-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --dev --locked

      - uses: iterative/setup-dvc@v1
      - name: Get data
        run: dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

      - name: Check data statistics
        run: uv run python src/mlops/dataset.py

      - name: Check data statistics & generate report
        run: |
          python src/example_mlops/data.py > data_statistics.md
          echo '![](./reports/figures/train_label_distribution.png "Train label distribution")' >> data_statistics.md
          echo '![](./reports/figures/test_label_distribution.png "Test label distribution")' >> data_statistics.md

      - name: Setup cml
        uses: iterative/setup-cml@v2

      - name: Comment on PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create data_statistics.md --watermark-title="Data Checker" # (1)!
