name: DVC Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.dvc"
      - ".dvc/**"

jobs:
  run-data-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --dev --locked

      - uses: iterative/setup-dvc@v1
      - name: Get data
        run: dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

      - name: Check data statistics
        run: uv run python src/mlops/dataset.py
